# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  - group: GitHub-Secrets
  - name: GITHUB_USER
    value: $(GITHUB_USER) # Use from variable group
  - name: GITHUB_PAT
    value: $(GITHUB_PAT) # Use from variable group

steps:
- checkout: self

- script: |
    echo "Checking GitHub connection..."
    git remote remove github || true

    git remote add github https://$GITHUB_USER:$GITHUB_PAT@github.com/aporquis/BasilandByte.git

    echo "Current remote settings:"
    git remote -v

    echo "Testing authentication..."
    git ls-remote github
  displayName: 'Test GitHub Connection'
  