# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - AzureMirror

pool:
  vmImage: ubuntu-latest

variables:
  - group: GitHub-Secrets
  - name: GITHUB_USER
    value: $(GITHUB_USER) # Use from variable group
  - name: GITHUB_PAT
    value: $(GITHUB_PAT) # Use from variable group

steps:
- checkout: self

- script: |
    echo "Setting up GitHub remote..."
    if git remote get-url github; then
      echo "Remote 'github' already exists. Updating URL..."
      git remote set-url github https://$GITHUB_USER:$GITHUB_PAT@github.com/aporquis/BasilandByte.git
    else
      echo "Adding remote 'github'..."
      git remote add github https://$GITHUB_USER:$GITHUB_PAT@github.com/aporquis/BasilandByte.git
    fi
    echo "Pushing to GitHub..."
    git push github main
  displayName: 'Mirror to GitHub'