# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  - group: GitHub-Secrets
  - name: GITHUB_USER
    value: $(GITHUB_USER) # Use from variable group
  - name: GITHUB_PAT
    value: $(GITHUB_PAT) # Use from variable group

steps:
- checkout: self

- script: |
- script: |
    echo "Current remote settings:"
    git remote -v

    echo "Listing remote branches:"
    git branch -a

    echo "Fetching remote refs..."
    git fetch --all

    echo "Listing after fetch:"
    git branch -a
  displayName: 'Test GitHub Connection and Fetch'
  