# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  - group: GitHub-Secrets
  - name: GITHUB_USER
    value: $(GITHUB_USER) # Use from variable group
  - name: GITHUB_PAT
    value: $(GITHUB_PAT) # Use from variable group

steps:
- checkout: self

- script: |
    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    echo "Current branch is $CURRENT_BRANCH"

    echo "Setting up GitHub remote..."
    if git remote get-url github; then
      git remote set-url github https://$GITHUB_USER:$GITHUB_PAT@github.com/aporquis/BasilandByte.git
    else
      git remote add github https://$GITHUB_USER:$GITHUB_PAT@github.com/aporquis/BasilandByte.git
    fi

    echo "Checking for commits..."
    if [ -z "$(git log --oneline)" ]; then
      echo "No commits found. Creating an empty commit."
      git commit --allow-empty -m "Initial commit to enable sync"
    fi

    echo "Pushing current branch to GitHub..."
    git push github $CURRENT_BRANCH || echo "No branch to push"

    echo "Pushing all tags..."
    git push github --tags || echo "No tags to push"
  displayName: 'Mirror all branches and tags to GitHub'
  