# Generated by Django 4.2.18 on 2025-03-20 02:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_weeklyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('source', models.CharField(choices=[('mobile', 'Mobile'), ('web', 'Web')], default='unknown', max_length=10)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
