# Generated by Django 4.2.18 on 2025-04-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_ingredient_image_userinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Side Dishes', 'Side Dishes')], default='Dinner', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['ingredient_name'], name='ingredient_name_idx'),
        ),
    ]
