# Generated by Django 4.2.18 on 2025-04-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_image_recipe_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='image',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
