# Generated by Django 4.2.18 on 2025-04-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_accountreactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinventory',
            name='quantity_display',
            field=models.CharField(default=1, help_text="User-friendly string (e.g., '1 1/2')", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userinventory',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='Numeric Version for calculations', max_digits=6),
        ),
    ]
