name: Sync to Azure DevOps
on:
  push:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test Azure connection
        run: |
          echo "Setting up Azure remote..."
          git remote add azure https://$AZURE_USER:$AZURE_PAT@dev.azure.com/CS480Spring25/BasilAndByte/_git/BasilAndByte ||
          git remote set-url azure https://$AZURE_USER:$AZURE_PAT@dev.azure.com/CS480Spring25/BasilAndByte/_git/BasilAndByte

          echo "Current remotes:"
          git remote -v

          echo "Testing connection to Azure..."
          git ls-remote azure
        env:
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_PAT: ${{ secrets.AZURE_PAT }}