name: Sync to Azure DevOps
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Push to Azure DevOps
        run: |
          git remote add azure https://$AZURE_USER:$AZURE_PAT@dev.azure.com/CS480Spring25/BasilAndByte/_git/BasilAndByte
          git push azure main
        env:
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_PAT: ${{ secrets.AZURE_PAT }}