name: Sync to Azure DevOps
on:
  push:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Test Azure connection
        run: |
          echo "Setting up Azure remote..."
          git remote add azure https://$AZURE_USER:$AZURE_PAT@dev.azure.com/CS480Spring25/BasilAndByte/_git/BasilAndByte || \
          git remote set-url azure https://$AZURE_USER:$AZURE_PAT@dev.azure.com/CS480Spring25/BasilAndByte/_git/BasilAndByte

          echo "Current remotes:"
          git remote -v

          echo "Testing connection to Azure..."
          git ls-remote azure
        env:
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_PAT: ${{ secrets.AZURE_PAT }}

      - name: Push to Azure DevOps
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "Current branch is $CURRENT_BRANCH"

          if [ -z "$CURRENT_BRANCH" ]; then
            echo "No branch detected. Skipping push."
          else
            echo "Pushing branch $CURRENT_BRANCH to Azure (force)..."
            git push azure $CURRENT_BRANCH --force || echo "Failed to push branch"
          fi

          echo "Pushing all branches (force)..."
          git push azure --all --force || echo "Failed to push all branches"

          echo "Pushing all tags..."
          git push azure --tags || echo "Failed to push tags"
        env:
          AZURE_USER: ${{ secrets.AZURE_USER }}
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
